import type { DuomeiNote } from "./noteTypes";

const now = "2026-06-29T00:00:00.000Z";

export const defaultNotes: DuomeiNote[] = [
  {
    id: "note-osaka-first-day",
    slug: "osaka-first-day",
    title: "大阪的第一天",
    date: "2025.05.12",
    location: "大阪",
    category: "旅途记录",
    tags: ["大阪", "初到", "街道"],
    excerpt: "抵达大阪的那天，风从车站口吹过来，像把新的生活翻开第一页。",
    body: "第一次把行李放下的时候，城市还很陌生。通天阁、商店街、便利店的灯，一点点把我带进大阪的日常。那天没有特别伟大的事情发生，只是我知道，新的记录从这里开始。",
    coverImageUrl: "",
    bodyImages: [],
    contentBlocks: [],
    stylePrompt: "米白底、手绘线条、大阪街道、通天阁、低饱和浅棕和浅绿",
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "note-hankai-sea",
    slug: "hankai-tram-sea",
    title: "和阪堺电车一起看海",
    date: "2025.05.15",
    location: "阪堺电车",
    category: "旅行照片",
    tags: ["电车", "海边", "大阪"],
    excerpt: "绿色电车慢慢开向海边，窗外的光像旧照片一样温柔。",
    body: "阪堺电车不快，正好适合看风景。轨道旁边的房子、海风、远处的蓝色，都像是在提醒我：慢一点也可以抵达。",
    coverImageUrl: "",
    bodyImages: [],
    contentBlocks: [],
    stylePrompt: "日系手绘、阪堺电车、海边、浅绿色电车、米白背景",
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "note-kyoto-slow-time",
    slug: "kyoto-slow-time",
    title: "京都，慢下来的时光",
    date: "2025.05.18",
    location: "京都",
    category: "心情文字",
    tags: ["京都", "散步", "慢"],
    excerpt: "京都像一段被放慢的声音，走进去之后，人也自然轻下来。",
    body: "在京都散步的时候，我总会少拍一点，多看一点。木门、石板路、寺院的屋檐，都不急着向人解释自己。",
    coverImageUrl: "",
    bodyImages: [],
    contentBlocks: [],
    stylePrompt: "京都街道、木屋、塔、浅灰线条、淡棕色阴影、安静",
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "note-maizuru-wind",
    slug: "maizuru-sea-wind",
    title: "舞鹤的海风",
    date: "2025.05.21",
    location: "舞鹤",
    category: "旅途记录",
    tags: ["舞鹤", "海风", "港口"],
    excerpt: "海风把舰影和人群吹得很轻，那一天像被放进了蓝色档案袋。",
    body: "舞鹤的海不是喧闹的海。它更像一页安静的记录，风、船、远处的声音，都有一点金属和盐的味道。",
    coverImageUrl: "",
    bodyImages: [],
    contentBlocks: [],
    stylePrompt: "舞鹤港口、海风、淡蓝灰、手绘船影、低饱和",
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "note-guilin-memory",
    slug: "guilin-mountains",
    title: "桂林山水",
    date: "2025.05.25",
    location: "桂林",
    category: "生活记录",
    tags: ["桂林", "故乡", "山水"],
    excerpt: "桂林的山总在记忆里，不说话，却一直像路标一样存在。",
    body: "离开以后，才发现故乡不是一个固定地点。它会变成山的形状、水的颜色，跟着我去很多地方。",
    coverImageUrl: "",
    bodyImages: [],
    contentBlocks: [],
    stylePrompt: "桂林山水、米白纸面、浅绿山影、细线小船、安静留白",
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "note-after-night-shift",
    slug: "morning-after-night-shift",
    title: "夜勤后的清晨",
    date: "2025.06.02",
    location: "大阪",
    category: "生活记录",
    tags: ["夜勤", "清晨", "日本生活"],
    excerpt: "夜勤后的早晨很轻，便利店灯光还亮着，人却像慢慢回到自己身体里。",
    body: "下班的时候天刚亮。街道上人不多，空气里有一点冷。这样的清晨不一定适合拍照，却很适合记下来。",
    coverImageUrl: "",
    bodyImages: [],
    contentBlocks: [],
    stylePrompt: "清晨街道、便利店灯光、浅灰米白、一个人的背影、手绘线条",
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
];
