import type { CmsState, ContentItem } from "./cmsTypes";

const now = "2026-06-28T00:00:00.000Z";

export const defaultItems: ContentItem[] = [
  {
    id: "journey-maizuru",
    slug: "maizuru-fleet-festa",
    type: "journey",
    title: "舞鶴 Fleet Festa",
    subtitle: "Kyoto / Maizuru",
    date: "2026.05",
    location: "Kyoto / Maizuru",
    category: "Travel",
    tags: ["Travel", "Festival", "Sea"],
    excerpt: "海风、舰影和人群之间，一天慢慢展开成蓝色的记忆。",
    body: "舞鹤的海风带着一点金属味。舰影、队列、人群和远处的蓝色，让这一天像被慢慢夹进档案袋里的照片。",
    coverImageUrl: "",
    galleryImages: [],
    status: "published",
    showOnHome: true,
    featured: true,
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "journey-miho",
    slug: "miho-air-festival",
    type: "journey",
    title: "美保基地航空祭",
    subtitle: "Tottori / Miho",
    date: "2026.05",
    location: "Tottori / Miho",
    category: "Festival",
    tags: ["Airshow", "Photo", "Tottori"],
    excerpt: "抬头看飞机划过云层，也记录一个人站在跑道旁的安静。",
    body: "飞机划过云层的时候，人群会一起抬头。那一瞬间，旅行不只是抵达地点，也是在陌生地方和别人共享同一个方向。",
    status: "published",
    showOnHome: true,
    featured: true,
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "journey-sakai",
    slug: "sakai-festival",
    type: "journey",
    title: "堺の祭り",
    subtitle: "Osaka / Sakai",
    date: "2026.04",
    location: "Osaka / Sakai",
    category: "Festival",
    tags: ["Sakai", "Street", "Festival"],
    excerpt: "熟悉的街道突然热闹起来，像生活给自己换了一件外衣。",
    body: "平时走过很多次的街道，因为祭典变得不一样。灯、摊位、孩子的声音，让日常多出一层柔软的亮光。",
    status: "published",
    showOnHome: true,
    featured: false,
    order: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "journey-lotus",
    slug: "shirasagi-lotus",
    type: "journey",
    title: "白鷺公園の蓮",
    subtitle: "Osaka / Shirasagi",
    date: "2026.07",
    location: "Osaka / Shirasagi",
    category: "Nature",
    tags: ["Nature", "Lotus", "Walk"],
    excerpt: "荷叶、微风、远处的日语闲谈，夏天在水面上停了一会。",
    body: "白鹭公园的荷花不急着成为景点。它们只是在水面上慢慢打开，像提醒我夏天也可以安静地经过。",
    status: "published",
    showOnHome: true,
    featured: false,
    order: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "journey-osaka",
    slug: "osaka-solo-walk",
    type: "journey",
    title: "大阪ひとり散歩",
    subtitle: "Osaka",
    date: "2026.03",
    location: "Osaka",
    category: "Street",
    tags: ["Solo Travel", "Street", "Osaka"],
    excerpt: "没有计划的散步，把便利店灯光和傍晚车站都放进相机。",
    body: "一个人在大阪散步的时候，最容易注意到小东西：便利店门口的灯、车站台阶、傍晚的自行车铃声。",
    status: "published",
    showOnHome: true,
    featured: false,
    order: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "journey-guilin",
    slug: "guilin-memory",
    type: "journey",
    title: "桂林の記憶",
    subtitle: "China / Guilin",
    date: "Memory",
    location: "China / Guilin",
    category: "China Memory",
    tags: ["Guilin", "Memory", "Home"],
    excerpt: "山水不是背景，是从很远的地方一直跟着我的起点。",
    body: "桂林的山水不是明信片，而是记忆里一种很早就存在的尺度。后来走到大阪、鸟取、京都，也会隐约拿它来比照。",
    status: "published",
    showOnHome: true,
    featured: true,
    order: 6,
    createdAt: now,
    updatedAt: now,
  },
  ...[
    ["station-after-rain", "Station After Rain", "Street", "大阪雨后的站台"],
    ["maizuru-harbor", "Maizuru Harbor", "Travel", "海边的舰影"],
    ["festival-lantern", "Festival Lantern", "Festival", "祭典灯火"],
    ["lotus-morning", "Lotus Morning", "Nature", "白鹭公园的荷"],
    ["night-shift-dawn", "Night Shift Dawn", "Care Life", "夜勤后的清晨"],
    ["guilin-hillline", "Guilin Hillline", "China Memory", "桂林山影"],
    ["sakai-corner", "Sakai Corner", "Street", "街角与自行车"],
    ["yonago-window", "Yonago Window", "Travel", "旅馆窗边"],
    ["paper-crane", "Paper Crane", "Care Life", "介护现场的小纸鹤"],
    ["summer-shrine", "Summer Shrine", "Festival", "夏日神社"],
    ["river-memory", "River Memory", "China Memory", "记忆里的水边"],
    ["cloud-gap", "Cloud Gap", "Nature", "云缝里的光"],
  ].map(([slug, title, category, excerpt], index) => ({
    id: `photo-${slug}`,
    slug,
    type: "photo" as const,
    title,
    subtitle: excerpt,
    date: "2026",
    location: category,
    category,
    tags: [category],
    excerpt,
    body: `${excerpt}。这是一张被放进 TAMI 数字档案馆的摄影记录。`,
    status: "published" as const,
    showOnHome: true,
    featured: index < 4,
    order: index + 1,
    createdAt: now,
    updatedAt: now,
  })),
  ...[
    ["tengwangge", "《滕王阁序》摘记", "落霞与孤鹜齐飞，秋水共长天一色。", "好的景色不是热闹，而是天地忽然对齐，让人意识到自己也在其中。"],
    ["chibifu", "《赤壁赋》摘记", "寄蜉蝣于天地，渺沧海之一粟。", "人在旅途中会变小，但也因为变小，才看见更大的水面和月光。"],
    ["lanting", "《兰亭集序》摘记", "仰观宇宙之大，俯察品类之盛。", "从抬头到低头，是一种观看世界的方法，也像摄影里的远景和细节。"],
    ["classical-travel", "古文里的旅行感", "风烟俱净，天山共色。", "古人的路常常很慢，所以一句风景里会藏着路程、天气和心情。"],
    ["mountain-home", "山水、离别与归乡", "仍怜故乡水，万里送行舟。", "所谓故乡，也许就是离开后仍然替你送行的那一部分。"],
  ].map(([slug, title, quote, thought], index) => ({
    id: `note-${slug}`,
    slug,
    type: "note" as const,
    title,
    subtitle: quote,
    date: "2026",
    category: "Classical Notes",
    tags: ["古文", "札记"],
    excerpt: thought,
    body: `${quote}\n\n${thought}`,
    status: "published" as const,
    showOnHome: true,
    featured: index < 2,
    order: index + 1,
    createdAt: now,
    updatedAt: now,
  })),
  ...[
    ["kansai-solo-travel", "一个人在关西旅行", "Travel"],
    ["morning-after-night-shift", "夜勤后的清晨", "Care Life"],
    ["personal-website-reason", "为什么我想做自己的个人网站", "Web"],
    ["photo-not-proof", "摄影不是为了证明去过哪里", "Photo"],
    ["care-japanese-language", "在日本介护现场学到的语言", "Japanese"],
  ].map(([slug, title, category], index) => ({
    id: `essay-${slug}`,
    slug,
    type: "essay" as const,
    title,
    subtitle: category,
    date: "2026",
    category,
    tags: [category],
    excerpt: "一篇关于旅行、摄影、介护工作和日本生活的个人文字。",
    body: "这篇文章保存在多美数字档案馆里。它不是为了成为结论，而是为了给当时的生活留一个可返回的位置。",
    status: "published" as const,
    showOnHome: true,
    featured: index < 2,
    order: index + 1,
    createdAt: now,
    updatedAt: now,
  })),
  ...[
    "这张照片像是夜勤后的清晨，安静但没有完全醒来。",
    "你拍的不是景点，是一个人抵达某个地方的证据。",
    "桂林和大阪之间，好像一直有一条看不见的路。",
    "下次可以试试把人物放在画面边缘，让孤独感更明显。",
  ].map((body, index) => ({
    id: `ai-wall-${index + 1}`,
    slug: `ai-wall-${index + 1}`,
    type: "ai-wall" as const,
    title: `AI Note ${String(index + 1).padStart(2, "0")}`,
    date: "2026",
    category: "AI Memory",
    tags: ["AI", "Memory"],
    excerpt: body,
    body,
    status: "published" as const,
    showOnHome: true,
    featured: false,
    order: index + 1,
    createdAt: now,
    updatedAt: now,
  })),
];

export const defaultContent: CmsState = {
  items: defaultItems,
  profile: {
    name: "TAMI",
    displayName: "多美",
    bio: "多美，中国桂林人，现在在大阪生活和工作。平时做介护工作，也喜欢一个人旅行、拍照、记录日本生活、学习日语和古文。这个网站不是简历，而是一个长期保存记忆、照片、文章和路上心情的地方。",
    location: "Osaka / Sakai",
    origin: "Guilin",
    occupation: "Care Worker",
    interests: ["Photography", "Solo Travel", "Classical Chinese", "Japanese Study"],
    avatarUrl: "",
  },
  settings: {
    siteTitle: "TAMI Digital Archive",
    siteSubtitle: "Journey, Photography, Classical Notes, Essays and AI Memories.",
    introYear: "2026",
    heroEyebrow: "TAMI PERSONAL ARCHIVE",
    heroTitle: "多美数字档案馆",
    heroDescription: "这里保存多美的旅程、摄影、古文札记、文章、日本生活、介护工作记忆，以及 AI 旅伴留下的留言。",
    primaryButtonText: "查看旅程",
    secondaryButtonText: "阅读文章",
    contactText: "如果你想交流旅行、摄影、网站、文章，或者只是想看我继续记录生活，可以从这里联系我。",
    instagramUrl: "https://instagram.com/",
    email: "hello@example.com",
    githubUrl: "https://github.com/",
  },
};
