import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
// @ts-expect-error Node's strip-types test runner needs the explicit source extension.
import * as adminSiteInventory from "./adminSiteInventory.ts";
// @ts-expect-error Node's strip-types test runner needs the explicit source extension.
import { containFloatingWidget } from "./floatingWidget.ts";

const css = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../header-tablet-nav.css"), "utf8");
const appSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../App.tsx"), "utf8");
const headerSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/DuomeiHeader.tsx"), "utf8");
const backToTopSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/BackToTopButton.tsx"), "utf8");
const guyuPreviewSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/GuyuShelfPreview.tsx"), "utf8");
const noteDetailSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiNoteDetailPage.tsx"), "utf8");
const footerSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/DuomeiFooter.tsx"), "utf8");
const yunyouSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/YunyouSection.tsx"), "utf8");
const yunyouCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/YunyouSection.css"), "utf8");
const yunyouPageSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiYunyouPage.tsx"), "utf8");
const yunyouPageCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../yunyou-page.css"), "utf8");
const zaobaoSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/ZaobaoSection.tsx"), "utf8");
const zaobaoCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/ZaobaoSection.css"), "utf8");
const zaobaoPageSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiZaobaoPage.tsx"), "utf8");
const zaobaoArchivePageSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiZaobaoArchivePage.tsx"), "utf8");
const xunjiSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/XunjiSection.tsx"), "utf8");
const xunjiCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/XunjiSection.css"), "utf8");
const xunjiPageSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiXunjiPage.tsx"), "utf8");
const xunjiEditionSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "./xunjiEdition.ts"), "utf8");
const xunjiArchivePageSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiXunjiArchivePage.tsx"), "utf8");
const homeIntroSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/HomeIntroSection.tsx"), "utf8");
const skillsSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/SkillsDirectory.tsx"), "utf8");
const skillsPageSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiSkillsPage.tsx"), "utf8");
const skillsCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../skills.css"), "utf8");
const homePageSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiHomePage.tsx"), "utf8");
const musicPlayerSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/DuomeiMusicPlayer.tsx"), "utf8");
const musicPlayerCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../music-player.css"), "utf8");
const neteaseClientSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "./neteasePlaylist.ts"), "utf8");
const neteaseServerSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../server/neteaseMusic.mjs"), "utf8");
const yunyouIndex = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../public/yunyou/index.html"), "utf8");
const yunyouMain = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../public/yunyou/src/main.js"), "utf8");
const yunyouLandmarks = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../public/yunyou/data/landmarks.js"), "utf8");
const yunyouCover = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../public/images/yunyou-guilin-cover.webp"));
const prValidationWorkflow = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../.github/workflows/pr-validation.yml"), "utf8");
const cursorAutoMergeWorkflow = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../.github/workflows/cursor-auto-merge.yml"), "utf8");
const edgeOneDeployWorkflow = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../.github/workflows/deploy-edgeone.yml"), "utf8");
const edgeOneConfig = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../edgeone.json"), "utf8");
const guyuCarouselSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "./guyuCarousel.ts"), "utf8");
const guyuCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../guyu.css"), "utf8");
const guyuReaderPageSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiGuyuReaderPage.tsx"), "utf8");
const homeIntroCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../components/HomeIntroSection.css"), "utf8");
const siteCss = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../styles.css"), "utf8");
const rootIndex = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../../index.html"), "utf8");
const adminSource = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "../pages/DuomeiAdmin.tsx"), "u